conv:
  n_conv_layers: 2
  conv_kernel_size: 3
  dropout: 0.1

hubert:
  model_name: rinna/japanese-hubert-base
  encoder_output_dim: 768
  kmeans: hifi_captain
  n_clusters: 200
  ignore_index: 0
  freeze: true

vocoder_input_cluster: hubert
