conv:
  n_conv_layers: 2
  conv_kernel_size: 3
  dropout: 0.1
  freeze: true

hubert:
  model_name: rinna/japanese-hubert-base
  encoder_output_dim: 768
  kmeans: hifi_captain
  n_clusters: 200
  ignore_index: 0
  freeze: false
  encoder_input_mask:
    use: true
    mask_prob: 0.8
    mask_length: 10

vocoder_input_cluster: hubert
