max_epoch: 20
batch_size: 8
num_workers: 8
input_sec: 10
seed: 42
monitoring_metric: "val_loss"
monitoring_mode: "min"
early_stopping_patience: 5
save_checkpoint_every_n_epochs: 1
save_checkpoint_top_k: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
log_every_n_steps: 10
precision: "16-mixed"
accumulate_grad_batches: 2
gradient_clip_val: 3.0
gradient_clip_algorithm: "norm"
checkpoints_save_dir: "~/lip2sp/checkpoints"
wandb:
  project_name: "lip2sp-pytorch-lightning-prod"
  default_root_dir: "./"
  run_name:
  group_name:
augs:
  random_crop:
    use: true
  horizontal_flip:
    use: true
  time_masking:
    use: true
    max_masking_sec: 0.5
