max_epoch: 15
batch_size: 8
num_workers: 8
input_sec: 1
seed: 42
monitoring_metric: "val_loss_gen_stft"
monitoring_mode: "min"
early_stopping_patience: 5
save_checkpoint_every_n_epochs: 1
save_checkpoint_top_k: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
log_every_n_steps: 10
precision: "16-mixed"
checkpoints_save_dir: "~/lip2sp/checkpoints/pwg"
n_fft_list : [320, 640, 1280]
hop_length_list : [80, 160, 320]
win_length_list : [320, 640, 1280]
stft_loss_weight : 1.0
gan_loss_weight : 4.0
finetune: true
finetune_start_model_path: "/home/minami/lip2sp/checkpoints/pwg/20240324_185245/epoch=13-step=132020-val_loss=0.000.ckpt"
wandb:
  project_name: "lip2sp-pwg"
  default_root_dir: "./"
  run_name:
  group_name:
augs:
  random_crop:
    use: false
  horizontal_flip:
    use: false
  time_masking:
    use: false
    max_masking_sec: 0.5
