program: ../src/main/base.py
project: lip2sp-base
name: test-ssl-20240325-1
method: grid
parameters:
  model.ssl_type:
    values: ["avhubert", "raven", "vatlm"]
metric:
  name: val_loss
  goal: minimize
command:
  - python
  - ${program}
  - ${args_no_hyphens}
