defaults:
  - avhubert: base
  - raven: base
  - vatlm: base
  - pwg: base
  - hifigan: base
  - decoder: config

spk_emb_layer:
  use: true
  dim: 256
  freeze: false

ssl_type: avhubert
ssl_feature_dropout: 0
