kablab:
  use: true
  # speaker: ["F01_kablab", "M01_kablab", "F02_kablab", "M04_kablab"]
  # corpus: ["ATR"]
  speaker: ["F01_kablab", "M01_kablab"]
  corpus: ["ATR", "BASIC5000", "balanced"]

jvs:
  use: false

hifi_captain:
  use: false

jsut:
  use: false
