kablab:
  audio_dir: "~/dataset/lip/wav"
  video_dir: "~/dataset/lip/avhubert_preprocess_fps25"
  hubert_feature_prj_output_dir: "~/dataset/lip/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/lip/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/lip/hubert/cluster/jsut"
  df_path: "~/dataset/lip/data_split.csv"
  emb_dir: "~/dataset/lip/emb"
  text_dir: "~/dataset/lip/utt"

jvs:
  audio_dir: "~/dataset/jvs_ver1_cut_silence"
  hubert_feature_prj_output_dir: "~/dataset/jvs_ver1_cut_silence/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/jvs_ver1_cut_silence/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/jvs_ver1_cut_silence/hubert/cluster/jsut"
  df_path: "~/dataset/jvs_ver1_cut_silence/data_split.csv"
  emb_dir: "~/dataset/jvs_ver1/emb"
  stat_path: "~/dataset/lip/stat/mel/jvs.npz"

hifi_captain:
  audio_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP"
  hubert_feature_prj_output_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/cluster/jsut"
  df_path: "~/dataset/hi-fi-captain_cut_silence/ja-JP/data_split.csv"
  emb_dir: "~/dataset/hi-fi-captain/ja-JP"
  stat_path: "~/dataset/lip/stat/mel/hi-fi-captain.npz"

jsut:
  audio_dir: "~/dataset/jsut_ver1.1_cut_silence"
  hubert_feature_prj_output_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/cluster/jsut"
  df_path: "~/dataset/jsut_ver1.1_cut_silence/data_split.csv"
  emb_dir: "~/dataset/jsut_ver1.1_cut_silence/emb"
  hubert_kmeans_path: "~/dataset/jsut_ver1.1_cut_silence/hubert/kmeans.pickle"

vctk:
  stat_path: "~/dataset/lip/stat/mel/vctk.npz"
