kablab:
  audio_dir: "~/dataset/lip/wav"
  audio_cut_silence_dir: "~/dataset/lip/wav_cut_silence" 
  video_dir: "~/dataset/lip/avhubert_preprocess_fps25"
  video_cut_silence_dir: "~/dataset/lip/avhubert_preprocess_fps25_cut_silence"
  hubert_feature_prj_output_dir: "~/dataset/lip/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/lip/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/lip/hubert/cluster_fix"
  hubert_kmeans_dir: "~/dataset/lip/hubert/kmeans_fix"
  df_path: "~/dataset/lip/data_split.csv"
  emb_dir: "~/dataset/lip/emb_fix"
  text_dir: "~/dataset/lip/utt"
  utt_csv_test_path: "~/lip2sp/csv/ATR503.csv"
  forced_alignment_results_dir: "~/dataset/lip/forced_alignment_results"
  onehot_encoder_dir: "~/dataset/lip/forced_alignment_results/onehot_encoders"
  cca_result_dir: "~/lip2sp/results/cca"
  hubert:
    conv_feature_dir: "~/dataset/lip/speech_ssl_features/hubert/conv_features"
    layer_feature_dir: "~/dataset/lip/speech_ssl_features/hubert/layer_features" 
    kmeans_dir: "~/dataset/lip/speech_ssl_features/hubert/kmeans" 
    layer_feature_cluster_dir: "~/dataset/lip/speech_ssl_features/hubert/layer_feature_clusters"
  wav2vec2:
    conv_feature_dir: "~/dataset/lip/speech_ssl_features/wav2vec2/conv_features"
    kmeans_dir: "~/dataset/lip/speech_ssl_features/wav2vec2/kmeans" 
  data2vec:
    conv_feature_dir: "~/dataset/lip/speech_ssl_features/data2vec-audio/conv_features"
    kmeans_dir: "~/dataset/lip/speech_ssl_features/data2vec-audio/kmeans" 

jvs:
  audio_dir: "~/dataset/jvs_ver1_cut_silence"
  video_dir:
  text_dir: "~/dataset/jvs_ver1"
  hubert_feature_prj_output_dir: "~/dataset/jvs_ver1_cut_silence/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/jvs_ver1_cut_silence/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/jvs_ver1_cut_silence/hubert/cluster_fix"
  df_path: "~/dataset/jvs_ver1_cut_silence/data_split_fix.csv"
  emb_dir: "~/dataset/jvs_ver1_cut_silence/emb_fix"
  stat_path: "~/dataset/lip/stat/mel/jvs.npz"
  hubert:
    conv_feature_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/hubert/conv_features"
    layer_feature_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/hubert/layer_features"
    kmeans_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/hubert/kmeans" 
    layer_feature_cluster_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/hubert/layer_feature_clusters"
  wav2vec2:
    conv_feature_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/wav2vec2/conv_features"
    kmeans_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/wav2vec2/kmeans" 
  data2vec:
    conv_feature_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/data2vec-audio/conv_features"
    kmeans_dir: "~/dataset/jvs_ver1_cut_silence/speech_ssl_features/data2vec-audio/kmeans" 

hifi_captain:
  audio_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP"
  video_dir:
  hubert_feature_prj_output_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/cluster_fix"
  hubert_kmeans_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/hubert/kmeans_fix"
  df_path: "~/dataset/hi-fi-captain_cut_silence/ja-JP/data_split.csv"
  emb_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/emb_fix"
  stat_path: "~/dataset/lip/stat/mel/hi-fi-captain.npz"
  hubert:
    conv_feature_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/hubert/conv_features"
    layer_feature_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/hubert/layer_features"
    kmeans_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/hubert/kmeans" 
    layer_feature_cluster_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/hubert/layer_feature_clusters"
  wav2vec2:
    conv_feature_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/wav2vec2/conv_features"
    kmeans_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/wav2vec2/kmeans" 
  data2vec:
    conv_feature_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/data2vec-audio/conv_features"
    kmeans_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP/speech_ssl_features/data2vec-audio/kmeans" 

jsut:
  audio_dir: "~/dataset/jsut_ver1.1_cut_silence"
  hubert_feature_prj_output_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/cluster"
  hubert_kmeans_dir: "~/dataset/jsut_ver1.1_cut_silence/hubert/kmeans"
  df_path: "~/dataset/jsut_ver1.1_cut_silence/data_split.csv"
  emb_dir: "~/dataset/jsut_ver1.1_cut_silence/emb"

vctk:
  stat_path: "~/dataset/lip/stat/mel/vctk.npz"
