kablab:
  audio_dir: "~/dataset/lip/wav"
  video_dir: "~/dataset/lip/avhubert_preprocess_fps25"
  hubert_feature_prj_output_dir: "~/dataset/lip/hubert/feature_prj_output"
  hubert_encoder_output_dir: "~/dataset/lip/hubert/encoder_output"
  hubert_cluster_dir: "~/dataset/lip/hubert/cluster/kablab_M01_F01"
  hubert_kmeans_path: "~/dataset/lip/hubert/kmeans/kablab_M01_F01.pickle"
  df_path: "~/dataset/lip/data_split_csv/kablab.csv"
  emb_dir: "~/dataset/lip/emb"
  text_dir: "~/dataset/lip/utt"

jvs:
  data_dir: "~/dataset/jvs_ver1_cut_silence"
  df_path: "~/dataset/lip/data_split_csv/jvs.csv"
  path_train: "~/dataset/lip/np_files/jvs/train"
  emb_dir: "~/dataset/jvs_ver1/emb"
  stat_path: "~/dataset/lip/stat/mel/jvs.npz"

hifi_captain:
  data_dir: "~/dataset/hi-fi-captain_cut_silence/ja-JP"
  df_path: "~/dataset/lip/data_split_csv/hifi_captain.csv"
  emb_dir: "~/dataset/hi-fi-captain/ja-JP"
  stat_path: "~/dataset/lip/stat/mel/hi-fi-captain.npz"

vctk:
  stat_path: "~/dataset/lip/stat/mel/vctk.npz"
