resblock: 1
# resblock_kernel_sizes: [3, 7, 11]
resblock_kernel_sizes: [3, 5, 7, 9, 11]
# resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5], [1, 3, 5], [1, 3, 5]]
# upsample_rates: [5, 4, 4, 2, 2]
upsample_rates: [5, 4, 2, 2, 2, 2]
upsample_initial_channel: 1024
# upsample_kernel_sizes: [11, 8, 8, 4, 4]
upsample_kernel_sizes: [11, 8, 4, 4, 4, 4]
input: ["mel", "hubert_layer_feature_cluster"]
embedding_dim: 128
model_path:
model_path_mel:
model_path_speech_ssl:
model_path_mel_speech_ssl: "/home/minami/lip2sp/checkpoints/hifigan_base_hubert_2/20241023_060247/epoch:27-step:36344.ckpt"
freeze: true
loss:
  n_mels: 80
  n_fft: 1024
  hop_length: 256
  win_length: 1024
