max_epoch: 50
batch_size: 4
num_workers: 8
input_sec: 10
seed: 42
monitoring_metric: "val_loss"
monitoring_mode: "min"
early_stopping_patience: 40
save_checkpoint_every_n_epochs: 1
save_checkpoint_top_k: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
log_every_n_steps: 10
precision: "16-mixed"
accumulate_grad_batches: 8
gradient_clip_val: 3.0
gradient_clip_algorithm: "norm"
checkpoints_save_dir: "~/lip2sp/checkpoints/base"
n_fft_list: [320, 640, 1280]
hop_length_list: [80, 160, 320]
win_length_list: [320, 640, 1280]
finetune: true
finetune_start_model_path: "/home/minami/lip2sp/checkpoints/base/20240407_135308/epoch=19-step=500-val_loss=2.418.ckpt"
optimizer:
  type: adamw
  learning_rate: 1.0e-3
  beta_1: 0.9
  beta_2: 0.98
  weight_decay: 1.0e-2
scheduler:
  type: cawr
  cycle_mult: 1.0
  min_lr: 1.0e-6
  warmup_steps: 0.1
  gamma: 1.0
wandb:
  project_name: "lip2sp-base"
  default_root_dir: "./"
  run_name:
  group_name:
augs:
  random_crop:
    use: true
  horizontal_flip:
    use: true
  time_masking:
    use: true
    max_masking_sec: 0.5
