defaults:
  - optimizer: adamw
  - scheduler: cawr
  - params: base
  # - optimizer: adam
  # - scheduler: exp
  # - params: pwg

params:
  # max_epoch: 3
  # early_stopping_patience: 2
  # limit_train_batches: 0.1
  # limit_val_batches: 0.1
  # limit_test_batches: 0.1
  wandb:
    project_name: "debug"
