defaults:
  - optimizer: adam
  - scheduler: exp
  - params: pwg

params:
  # max_epoch: 5
  # early_stopping_patience: 2
  limit_train_batches: 0.2
  limit_val_batches: 0.2
  limit_test_batches: 0.2
  wandb:
    project_name: "debug"
