defaults:
  - optimizer: adam
  - scheduler: exp
  - params: pwg

params:
  max_epoch: 3
  early_stopping_patience: 2
  limit_train_batches: 0.01
  limit_val_batches: 0.01
  limit_test_batches: 0.01
  wandb:
    project_name: "debug"
