max_epoch: 30
batch_size: 4
num_workers: 4
input_sec: 10
input_sec_hifigan: 1
seed: 42
monitoring_metric: "val_loss_mel"
monitoring_mode: "min"
early_stopping_patience: 40
save_checkpoint_every_n_epochs: 1
save_checkpoint_top_k: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
log_every_n_steps: 10
precision: "16-mixed"
accumulate_grad_batches: 4
gradient_clip_val: 3.0
gradient_clip_algorithm: "norm"
checkpoints_save_dir: "~/lip2sp/checkpoints/hifigan_multiple_ssl_finetuning"
finetune: false
finetune_start_model_path:
lip2sp_model_path: 
optimizer:
  type: adamw
  learning_rate: 2.0e-4
  beta_1: 0.8
  beta_2: 0.99
  weight_decay: 1.0e-2
scheduler:
  type: exp
  gamma: 0.9
wandb:
  project_name: "lip2sp-hifigan_multiple_ssl_finetuning"
  default_root_dir: "./"
  run_name:
  group_name:
augs:
  random_crop:
    use: false
  horizontal_flip:
    use: false
    p: 0.5
  time_masking:
    use: false
    max_masking_sec: 0.5
  random_erasing:
    use: false
    p: 0.5
    scale_min: 0.02
    scale_max: 0.33
    ratio_min: 0.3
    ratio_max: 3.3
    value: 0
  add_gaussian_noise:
    use: false
    kernel_size: 9
    sigma_min: 0.1
    sigma_max: 1.0
  spec_gaussian_blur:
    use: false
    snr_min: 10
    snr_max: 60
