max_epoch: 30
batch_size: 16
num_workers: 16
input_sec: 1
seed: 42
monitoring_metric: "val_loss_gen_stft"
monitoring_mode: "min"
early_stopping_patience: 5
save_checkpoint_every_n_epochs: 1
save_checkpoint_top_k: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
log_every_n_steps: 10
precision: "16-mixed"
checkpoints_save_dir: "~/lip2sp/checkpoints/pwg"
stft_loss_weight: 1.0
gan_loss_weight: 4.0
finetune: true
finetune_start_model_path: "/home/minami/lip2sp/checkpoints/pwg/20240324_185245/epoch=13-step=132020-val_loss=0.000.ckpt"
optimizer:
  type: adam
  learning_rate: 1.0e-3
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 1.0e-6
scheduler:
  type: exp
  gamma: 0.9
wandb:
  project_name: "lip2sp-pwg"
  default_root_dir: "./"
  run_name:
  group_name:
augs:
  random_crop:
    use: false
  horizontal_flip:
    use: false
  time_masking:
    use: false
    max_masking_sec: 0.5
