generator:
  in_channels: 1
  out_channels: 1
  hidden_channels: 64
  cond_channels: 80
  upsample_scales: [10, 4, 2, 2]
  n_layers: 30
  n_stacks: 3
  dropout: 0.1
  kernel_size: 3
  use_weight_norm: false

discriminator:
  in_channels: 1
  out_channels: 1
  hidden_channels: 64
  n_layers: 10
  kernel_size: 3
  use_weight_norm: false
  dropout: 0

model_path: "/home/minami/lip2sp/checkpoints/20240320_175246/epoch=4-step=200-val_loss=0.000.ckpt"
